### ISSUE TITLE
Build Win64

### ISSUE THREAD

**Issue by vu-son** [ipa320/schunk_modular_robotics#128]
Hi all,
im a newbie hier, can you tell me how can i build the pakages for windows 64-bits?
Thanks

**Comment by vu-son** [comment]
All what i need ist the schunk_libm5api & schunk_powercube_chain for windows 64-bits system. How can i achieve that?

**Comment by floweisshardt** [comment]
sorry, there is no windows support for this ROS package. please visit http://mobile.schunk-microsite.com/de/produkte/kontakt.html for windows support directly from Schunk.
