### ISSUE TITLE
[schunk_sdhx] Finalize sdhx_driver 

### ISSUE THREAD

**Issue by fmessmer** [ipa320/schunk_modular_robotics#137]
...after next firmware upgrade.
Including extensive testing!

**Comment by fmessmer** [comment]
This is WONTFIX...as it has been decided to go for another solution...

**Comment by mathias-luedtke** [comment]
this can be closed, `sdhx_driver` package could be removed..

**Comment by fmessmer** [comment]
removed package in #186
