### ISSUE TITLE
problem with arm_base_link.stl

### ISSUE THREAD

**Issue by VahidAminZ** [ipa320/schunk_modular_robotics#150]
We used to be able to visualize the arm_base_link.stl with rviz before but the new version fails as it requires that the length of the stl file be (84 + number_of_triangles*50) and arm_base_link.stl has a single extra byte.
Deleting the extra byte at the end of the stl fixes the problem.

**Comment by fmessmer** [comment]
What arm are you referring to?
lwa, lwa_extended, lwa4d, lwa4p, lwa4p_extended?

**Comment by VahidAminZ** [comment]
lwa4p

**Comment by athackst** [comment]
I see this as well

**Comment by fmessmer** [comment]
#151 solves this issue
