### ISSUE TITLE
[lwa-4d] Rotation mismatch

### ISSUE THREAD

**Issue by athackst** [ipa320/schunk_modular_robotics#154]
Hi, 
I'm seeing a different axis of rotation on the prl+ joints from what the URDF model indicates.  In particular the axis of rotation seems to be pointing toward the base of the robot (positive delta = clockwise rotation) as opposed to what the URDF indicates  -- rotation pointing toward the end effector (positive delta = counter clockwise rotation).  I have checked to make sure my arm is using the default settings.  Are other people having this issue?  Should the model be updated to match the arm or is it better if I flip the direction of the motor in firmware?  Schunk seemed to indicated changing direction in firmware would not be ideal.

**Comment by fmessmer** [comment]
I don't know in what state the LWA4D robots are shipped by the manufacturer, at IPA however, we tried to follow the (Denavit-Hartenberg) convention, letting the axis of rotation of a joint point towards the next joint (towards the end-effector!). Thus, you might want to check the PRL modules with the Schunk configuration software what is set for the direction of rotation and adjust accordingly...
Hope this helpfs!

**Comment by athackst** [comment]
The frames can point the same direction, but I think the `<axis>` tag should be negated.  

i.e  `<axis xyz="0 0 -1"/>` instead of `<axis xyz="0 0 1"/>`

Do you have any LWA4D robots you could check?

**Comment by fmessmer** [comment]
I think this has been fixed in indigo_dev already...but it is likely that it hasn't been released yet.
I actually tested and modified this when working with our HW. Are you using debs or the source?
Can't see any -1 in the source for lwa4d

**Comment by athackst** [comment]
I'm using the source from this repo (indigo_dev).  I think it should have -1's, but it doesn't.

**Comment by fmessmer** [comment]
why would you want -1? DH says to point positive z-axis towards next joint, isn't it?

**Comment by athackst** [comment]
Because that's the direction of the default orientation of the motors in the arm.  So it's whether or not the URDF should match the hardware or the convention.  Do you guys really adjust all your hardware?

**Comment by fmessmer** [comment]
Maybe we did it and then did not know about the default state anymore. At least I don't. Can't tell atm how it should be.. Our HW is used by many people.

**Comment by fmessmer** [comment]
It just looked consistent this way

**Comment by athackst** [comment]
If you look at the firmware it would report "invert motor: yes" and "invert position: yes" if you did.  Otherwise the default is false for both.

**Comment by athackst** [comment]
I think it is probably best to leave it up to the user.  I added a parameter to the macro which will let you decide what is desired.  The default value follows the DH convention like before so no changes are forced upon others.
