### ISSUE TITLE
[lwa4p] URDF joint limits exceed manufacturer's specs?

### ISSUE THREAD

**Issue by Will-McMahan** [ipa320/schunk_modular_robotics#158]
Hi,

I noticed that the URDF joint limits for the lwa4p exceed the manufacturers' specs.  

http://mobile.schunk-microsite.com/fileadmin/user_upload/broshures/SCHUNK_Technical_data_LWA4P.pdf

Is this an error, or can the robot actually safely exceed the manufacturer's stated joint limits?

Thanks,
Will

**Comment by fmessmer** [comment]
It's possible that the limits in the URDF (min, max, velocity) are not according to the manufacturer specs...we haven't had a lwa4p hardware around to check
Please feel free to create a PullRequest with the according changes!

**Comment by fmessmer** [comment]
solved in #160
