### ISSUE TITLE
[schunk_description] sdh explodes in gazebo 2.2.3

### ISSUE THREAD

**Issue by guihomework** [ipa320/schunk_modular_robotics#172]
I instantiated a sdh model at the top of my lwr in gazebo on indigo, and got fingers exploding, usually coming from inter-penetrating collision objects.

![sdh_explodes_gazebo2](https://cloud.githubusercontent.com/assets/6583181/18591854/a9f3313e-7c34-11e6-8802-787925ff07c0.png)

I noticed that the palm and knuckle collision objects somehow inter-penetrate and are also quite detailed for collision objects.

Did you notice a similar behaviour ?

I will provide a PR with simplified collision models that do not inter-penetrate and hence with a model that does not explode in my gazebo simulation.

**Comment by guihomework** [comment]
Retested, and noticed a few things :
* happens only on gazebo 2.2.3, not on gazebo 7 (kinetic)
* happens if one adds gazebo_ros_control plugin (so might also be fixed by the kinetic version of this plugin not only gazebo version)
* can be fixed with palm_collision change only

**Comment by fmessmer** [comment]
Merged...Thanks!
