### ISSUE TITLE
[schunk_description] sdh has wrong/bad inertial

### ISSUE THREAD

**Issue by guihomework** [ipa320/schunk_modular_robotics#174]
Currently sdh has default inertial terms, which create some huge inertia and then bad arm behavior when controlled in torque mode gazebo.

Compared to a shadow hand inertial, one can see with gazebo inertia/mass display that it does not match the model.

![sdh_bad_inertial_transparent](https://cloud.githubusercontent.com/assets/6583181/18678787/81471fee-7f5d-11e6-8d41-d79ab424faf6.png)

How accurate should be a fix I am willing to provide ? I don't know were to find individual masses of each sdh element, but could give estimates and use correctly parametrized box inertial macro calls instead of default.

What do you think ?

**Comment by guihomework** [comment]
I used meshlab with the original stl, and following the [gazebo tutorial](http://gazebosim.org/tutorials?tut=inertia&cat=build_robot) to compute inertia and mass parameters from there. It is not so well explained on the scaling and material density level, but I think I have something acceptable now considering an all aluminum hand except a fake density for the palm to match the overall 1.95 kg.

If you like this https://github.com/ubi-agni/schunk_modular_robotics/commit/205ca05de8f6a2677a3605c6d1944b7b7bed61e6

and the result
![sdh_better_inertial](https://cloud.githubusercontent.com/assets/6583181/18703505/64b3e770-7fe6-11e6-9dcc-45b18f349bc3.png)

I could do a PR

**Comment by fmessmer** [comment]
@guihomework 
Please propose the PR

**Comment by guihomework** [comment]
@ipa-fxm Sorry for the delay, very busy recording data.
Will try to have a look at the exploding issue before the end of the week hopefully.

**Comment by fmessmer** [comment]
I merged #180...Thanks!
