### ISSUE TITLE
Melodic release

### ISSUE THREAD

**Issue by jschleicher** [ipa320/schunk_modular_robotics#206]
Could you please consider releasing (at least) the `schunk_description` package to `melodic`?

**Comment by fmessmer** [comment]
maybe we can release to melodic but ignore failing packages:
https://answers.ros.org/question/66545/to-ignore-some-pkgs-upon-release-by-bloom/

I will look into this next WE

**Comment by agutenkunst** [comment]
Any updates on this?

**Comment by NadiaHG** [comment]
Done!
 https://github.com/ipa320/schunk_modular_robotics-release#schunk_modular_robotics-melodic---0612-0
Released for melodic ignoring some packages (thanks @fmessmer for the suggestion) . PR to rosdistro is already open https://github.com/ros/rosdistro/pull/18854

**Comment by fmessmer** [comment]
@ipa-nhg as you bumped the version....please also release `0.6.12` into `indigo` and `kinetic`

**Comment by NadiaHG** [comment]
@fmessmer done!
