### ISSUE TITLE
sdh.urdf.xacro to sdh.urdf conversion issue

### ISSUE THREAD

**Issue by chaiban** [ipa320/schunk_modular_robotics#221]
I used ros conversion but it does not seem to work. The urdf is empty as below.

[sdh.urdf.txt](https://github.com/ipa320/schunk_modular_robotics/files/4203605/sdh.urdf.txt)

I am using kinetic.

rosrun xacro xacro --inorder sdh.urdf.xacro > sdh.urdf

Any suggestions on how to clear it ? 

Thank you

**Comment by fmessmer** [comment]
@chaiban 
the `sdh.urdf.xacro` only defines a [`xacro:macro`](https://github.com/ipa320/schunk_modular_robotics/blob/kinetic_dev/schunk_description/urdf/sdh/sdh.urdf.xacro#L8) that can be included in a higher level robot description, e.g. like this:

```
  <xacro:schunk_sdh name="gripper" parent="base_link">
    <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:schunk_sdh>
```

see also: http://wiki.ros.org/urdf/Tutorials/Using%20Xacro%20to%20Clean%20Up%20a%20URDF%20File#Macros
