### ISSUE TITLE
change cmake magic to distinguish between 32-bit and 64-bit

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/schunk_modular_robotics#73]
this bug is blocking us from having a hydro release.

@ipa-mdl can you please fix that by adapting from https://github.com/ipa320/cob_extern/blob/hydro_dev/libntcan/CMakeLists.txt. Please send a PR and I'll trigger a new release.

**Comment by fmessmer** [comment]
I am working on schunk_modular_robotics right now....
it seems I have a version with which catkin_make_isolated --install succeeds...

**Comment by floweisshardt** [comment]
perfect, @ipa-fxm please adjust the issue above too.

**Comment by fmessmer** [comment]
hopefully fixed by #74

**Comment by floweisshardt** [comment]
new release triggered
