### ISSUE TITLE
Use of target_pos and target_pos_horizon in PowerCubeCtrl::MoveVel

### ISSUE THREAD

**Issue by svenschneider** [ipa320/schunk_modular_robotics#83]
In the PowerCubeCtrl::MoveVel two target position vectors are declared:
- target_pos: https://github.com/ipa320/schunk_modular_robotics/blob/hydro_dev/schunk_powercube_chain/common/src/PowerCubeCtrl.cpp#L433
- target_pos_horizon: https://github.com/ipa320/schunk_modular_robotics/blob/hydro_dev/schunk_powercube_chain/common/src/PowerCubeCtrl.cpp#L434

In the following code, values are calculated for the target_pos_horizon vector:
https://github.com/ipa320/schunk_modular_robotics/blob/hydro_dev/schunk_powercube_chain/common/src/PowerCubeCtrl.cpp#L486

However, all the comparisons are performed on the target_pos vector:
https://github.com/ipa320/schunk_modular_robotics/blob/hydro_dev/schunk_powercube_chain/common/src/PowerCubeCtrl.cpp#L515

Is this the correct behavior?

**Comment by NadiaHG** [comment]
will not be fixed anymore do to new canopen driver: https://github.com/ipa320/ros_canopen
