### ISSUE TITLE
check length of lwa4p modules

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/schunk_modular_robotics#87]
from Román Navarro (Robotnik):
"I think that the arm link 4 of the arm doesn't have the correct length in the stl as well as in the coordinates defined in the lwap4.urdf.xacro. I think in the model it's longer (approx 6 cm) than the real one."

**Comment by thiagodefreitas** [comment]
@RomanRobotnik : please follow this thread.

**Comment by NadiaHG** [comment]
The stl model is wrong, it is longer than the real hardware. We asked schunk for a new CAD model. As soon as we have it , we will update the mesh file and the urdf.

https://github.com/RomanRobotnik thank you for the issue

**Comment by NadiaHG** [comment]
https://github.com/ipa-nhg/schunk_modular_robotics/compare/ipa320:hydro_dev...hydro_dev

**Comment by fmessmer** [comment]
seems to be fine with the new_model!

-> close?
