### ISSUE TITLE
Velocity Operation Mode in schunk_sdh

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/schunk_modular_robotics#91]
we have here a Schunk Dexterous Hand that we are using with ROS. I'm using the hydro version of the schunk_sdh package. We are able to move the hand in position operation mode using the dashboard.
I tried to use the velocity operation mode, changing the parameter OperationMode to velocity (in the configuration file sdh.yaml of schunk_hardware_config package) and publishing the velocities to the topic /sdh_controller/set_velocities but in this way the sdh does not move. I used as joint names the ones in the sdh.yaml configuration file and rad/s as unit. Moreover I noticed that if I publish a negative velocity the sdh_controller node gives the error:

[ERROR]: An exception was caught: cSDHErrorInvalidParameter: Invalid target velocity value (-2.864789 not in range [0.000000..157.895000])

as if only positive velocities are admitted. Exploring a little bit the code I think the problem should be in the function SetAxisTargetVelocity(axes_,velocities_) of the SDHLibrary, but I can't understand what's wrong.

**Comment by mathias-luedtke** [comment]
The operation mode was not passed to the SDH at startup, so the hand was still in position mode.
I have prepared a patched version, that needs to be tested.

**Comment by floweisshardt** [comment]
is fixed in #93. still needs to be tested on HW before merge.
